name: box-xray-tproxy-v2.1

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github"
      - "README.md"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 更新 update.json 文件
      - name: Update update.json
        run: |
          version=$(grep -oP 'version=\K[^ ]+' module.prop)
          versionCode=$(grep -oP 'versionCode=\K[^ ]+' module.prop)

          echo '{
            "version": "'"${version}"'",
            "versionCode": "'"${versionCode}"'",
            "zipUrl": "https://github.com/coomsn/box-xray-tproxy/releases/download/'"${version}"'/box-xray-tproxy-'${version}'.zip",
            "changelog": "https://github.com/coomsn/box-xray-tproxy/raw/main/CHANGELOG.md"
          }' > update.json

      # 提交并推送 update.json
      - name: Commit and push update.json
        run: |
          git config --local user.name "coomsn"
          git config --local user.email "acstudycn@gmail.com"
          git add update.json
          git commit -m "Update update.json for version $(grep -oP 'version=\K[^ ]+' module.prop)" || true
          git push -f origin main

      # 执行 build.sh 脚本
      - name: Run build.sh
        run: sh build.sh

      # 从 ZIP 文件中提取版本信息
      - name: Extract version from filename
        id: extract_version
        run: |
          zip_file=$(ls box-xray-tproxy-v*.zip)
          version=$(echo "$zip_file" | sed -E 's/box-xray-tproxy-v(.*).zip/v\1/')
          echo "VERSION=${version}" >> $GITHUB_ENV

      # 删除已有的 Release 和 Tag
      - name: Delete existing release and tag
        run: |
          release_id=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases \
            | jq '.[] | select(.tag_name == env.VERSION) | .id')

          if [ -n "$release_id" ]; then
            echo "Deleting existing release with ID: $release_id"
            gh api -X DELETE /repos/${{ github.repository }}/releases/$release_id
          fi

          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.VERSION }}$"; then
            echo "Deleting existing tag: ${{ env.VERSION }}"
            git push origin :refs/tags/${{ env.VERSION }}
          fi

      # 读取 CHANGELOG.md 文件作为发布说明
      - name: Read release notes from CHANGELOG.md
        id: get_release_notes
        run: |
          RELEASE_NOTES=$(cat CHANGELOG.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 上传 ZIP 文件并创建 GitHub release
      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: ${{ env.VERSION }}
          files: box-xray-tproxy-v*.zip
          body: ${{ env.RELEASE_NOTES }}
          prerelease: false
          generate_release_notes: false
